name: build-and-push

on:
  # Allows the ability to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

# Allow one concurrent deployment
concurrency:
  group: "push-docker-hub"
  cancel-in-progress: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout & set image tag based on the commit hash
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set env.IMAGE_TAG for our docker hub repo
        # https://dev.to/hectorleiva/github-actions-and-creating-a-short-sha-hash-8b7
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          imageTag=misirloutg/disguise:$calculatedSha
          echo "Will build and push" $imageTag
          echo "IMAGE_TAG=$imageTag" >> $GITHUB_ENV
      - name: Test, test, test
        run: echo ${{ env.IMAGE_TAG }}
